### ISSUE TITLE
cannot be installed under Contao 4.11.2

### ISSUE THREAD

**Issue by cmette** [heimrichhannot/contao-multi-column-editor-bundle#18] opened 2021-05-14 12:06 UTC
**Context**
Contao version: 4.11.2
Bundle version: latest
PHP version: 7.4.11

**Description**
Unfortunately cannot be installed under C4.11.2, if you try, it downgrades from symfony 5.2.8 to 4.3 and thus blocks all other bundles ... Can you fix that in a timely manner?

**Comment by Defcon0** [comment] 2021-05-14 12:15
Mhm, can you detect why the downgrade happens? Please require symfony framework ^5.0 and multi-column-editor-bundle explicitly and post the error message.

It seems to be a sub dependency (transitive) and not the direct deps in multi-column-editor-bundle. One of them might require symfony framework directly in its composer.json.

**Comment by cmette** [comment] 2021-05-14 13:05
Thanks for the quick answer, I'll test it as soon as possible, poss. but only on monday, i wish you a nice weekend!
OK. the cause seems the be the https://packagist.org/packages/heimrichhannot/contao-request-bundle, is not approved for symfony 5 yet, symfony/framework-bundle: ^3.4||^4.1.12

**Comment by koertho** [comment] 2021-05-17 07:02
Sure, our utils bundle and a lot of other bundles are fixed to symfony 3 or 4. That's not a bug, it's cause a lot of bundles need to be compatible with contao 4.4/symfony 3. Contao 4.11 works with symfony 4, there shouldn't be an issue. But in the next months I think we update the most bundles for 4.9, so also the minimum symfony version will change to 4 and support 5.

**Comment by cmette** [comment] 2021-05-17 07:08
yes - thanks - I don't think it's a bug either, **it just can't be installed** at the moment ...

**Comment by koertho** [comment] 2021-05-17 08:17
Yes, but that's an Composer issue. If the update to symfony 5 is already done and our extensions are installed afterwards, it don't don't get the downgrade done. I don't see anything we can do (aside from allowing symfony 5).

**Comment by koertho** [comment] 2021-08-04 08:26
This should be fixed as utils-bundle and request-bundle are now symfony 5 ready.

**Closed** 2022-05-31 14:33 UTC
